version: "3.3"
services:
  api:
    image: "books.fast:latest"
    depends_on:
        - db
        - testdb
    ports:
      - 8000:80
    env_file:
      - ../app/.dev.env
    volumes:
      - ../app/:/app/app/
    command: bash -c "while true; do sleep 1; done"

  db:
    image: "postgres:13"
    env_file:
      - ../app/.dev.env
    volumes:
      - app-db-data-dev:/var/lib/postgresql/data/pgdata

  testdb:
    image: "postgres:13"
    env_file:
      - ../app/.test.env
    volumes:
      - app-db-data-test:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ../app/.dev.env
    
volumes:
  app-db-data-dev:
  app-db-data-test:

networks:
  default:
    external:
      name: $NETWORK_NAME
