on:
  push:
    branches:
      - 'master'
name: Build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create app/.env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_POSTGRES_SERVER: devdb
        envkey_POSTGRES_USER: fastapiuser
        envkey_POSTGRES_PASSWORD: fastapipass
        envkey_POSTGRES_DB: books_dev
        envkey_PGADMIN_DEFAULT_EMAIL: admin@example.com
        envkey_PGADMIN_DEFAULT_PASSWORD: password        
        envkey_GOODREAD_API_URL: "https://www.goodreads.com/book/review_counts.json"
        envkey_GOODREAD_API_KEY: ${{ secrets.GOODREAD_API_KEY }}
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        file_name: app/.env
    - run: make build
